### ISSUE TITLE
Support for timestamp and timestamptz column types?

### ISSUE THREAD

**Issue by richardsmd** [ankane/pgslice#3] opened 2016-10-17 21:42 UTC
Is there any interest in supporting alternative column types?

I love the project but have timestamptz fields I need to partition on. Right now I'm just wrapping the --dry-run output in a sed script but it wouldn't be a large change. I think perhaps one option and a little additional logic
- `--column-type` (defaults: date; add timestamp, timestamptz)
- Detect column type in `sql_date` and provide appropriate format and ::type

Please let me know your thoughts on reviewing/accepting a contribution with this functionality.

Thanks,

Mike

**Comment by ankane** [comment] 2016-10-19 02:25
@richardsmd Can you explain more about what you're trying to accomplish? pgslice should work with timestamp and timestamptz columns as is.

**Comment by richardsmd** [comment] 2016-10-19 16:16
What isn't working is query optimization from the CHECK constraints on the child tables - they all get scanned.

Create a database, partition it, insert some data. Everything works

```bash
sudo -u postgres psql <<EOF
CREATE USER pgslice_tester WITH PASSWORD 'test_pgslice';
DROP DATABASE IF EXISTS pgslice_test;
CREATE DATABASE pgslice_test;
GRANT ALL PRIVILEGES ON DATABASE pgslice_test to pgslice_tester;
EOF

echo 'localhost:5432:pgslice_test:pgslice_tester:test_pgslice' >> ~/.pgpass
chmod 600 ~/.pgpass

psql -h localhost --user pgslice_tester pgslice_test <<EOF
CREATE TABLE events(
    id SERIAL,
    description VARCHAR(100),
    occurred_at timestamptz);
EOF

psql -h localhost --user pgslice_tester pgslice_test -c "SELECT * FROM events"

export PGSLICE_URL='postgresql://pgslice_tester:test_pgslice@localhost/pgslice_test'
pgslice prep events occurred_at month
pgslice add_partitions events --intermediate --future 3
pgslice swap events

psql -h localhost --user pgslice_tester pgslice_test <<EOF
INSERT INTO events (description, occurred_at) VALUES
    ('foo',  '2016-10-04 13:17:22.0-04'::timestamptz),
    ('bar',  '2016-10-09 15:47:22.0-04'::timestamptz),
    ('baz',  '2016-11-16 09:22:22.0-04'::timestamptz),
    ('spam', '2016-12-27 14:26:22.0-04'::timestamptz);
EOF
```

Now lets check the query plan...

```bash
psql -h localhost --user pgslice_tester pgslice_test -c "EXPLAIN SELECT * FROM events WHERE occurred_at BETWEEN '2016-10-01 00:00:00-0' AND '2016-11-01 00:00:00-0';"
#                                                                          QUERY PLAN
#---------------------------------------------------------------------------------------------------------------------------------------------------------------
# Append  (cost=0.00..58.60 rows=9 width=230)
#   ->  Seq Scan on events  (cost=0.00..0.00 rows=1 width=230)
#         Filter: ((occurred_at >= '2016-09-30 20:00:00-04'::timestamp with time zone) AND (occurred_at <= '2016-10-31 20:00:00-04'::timestamp with time zone))
#   ->  Seq Scan on events_201610  (cost=0.00..14.65 rows=2 width=230)
#         Filter: ((occurred_at >= '2016-09-30 20:00:00-04'::timestamp with time zone) AND (occurred_at <= '2016-10-31 20:00:00-04'::timestamp with time zone))
#   ->  Seq Scan on events_201611  (cost=0.00..14.65 rows=2 width=230)
#         Filter: ((occurred_at >= '2016-09-30 20:00:00-04'::timestamp with time zone) AND (occurred_at <= '2016-10-31 20:00:00-04'::timestamp with time zone))
#   ->  Seq Scan on events_201612  (cost=0.00..14.65 rows=2 width=230)
#         Filter: ((occurred_at >= '2016-09-30 20:00:00-04'::timestamp with time zone) AND (occurred_at <= '2016-10-31 20:00:00-04'::timestamp with time zone))
#   ->  Seq Scan on events_201701  (cost=0.00..14.65 rows=2 width=230)
#         Filter: ((occurred_at >= '2016-09-30 20:00:00-04'::timestamp with time zone) AND (occurred_at <= '2016-10-31 20:00:00-04'::timestamp with time zone))
#(11 rows)

# Check it with a ::date cast, in case that helps
psql -h localhost --user pgslice_tester pgslice_test -c "EXPLAIN SELECT * FROM events WHERE occurred_at BETWEEN '2016-10-01'::date AND '2016-11-01'::date;"
#                                          QUERY PLAN
#-----------------------------------------------------------------------------------------------
# Append  (cost=0.00..58.60 rows=9 width=230)
#   ->  Seq Scan on events  (cost=0.00..0.00 rows=1 width=230)
#         Filter: ((occurred_at >= '2016-10-01'::date) AND (occurred_at <= '2016-11-01'::date))
#   ->  Seq Scan on events_201610  (cost=0.00..14.65 rows=2 width=230)
#         Filter: ((occurred_at >= '2016-10-01'::date) AND (occurred_at <= '2016-11-01'::date))
#   ->  Seq Scan on events_201611  (cost=0.00..14.65 rows=2 width=230)
#         Filter: ((occurred_at >= '2016-10-01'::date) AND (occurred_at <= '2016-11-01'::date))
#   ->  Seq Scan on events_201612  (cost=0.00..14.65 rows=2 width=230)
#         Filter: ((occurred_at >= '2016-10-01'::date) AND (occurred_at <= '2016-11-01'::date))
#   ->  Seq Scan on events_201701  (cost=0.00..14.65 rows=2 width=230)
#         Filter: ((occurred_at >= '2016-10-01'::date) AND (occurred_at <= '2016-11-01'::date))
#(11 rows)
```
Inserting data works but we're doing a full scan of all the child tables. This is unacceptable if you're planning on keeping the data around very long (possibly not your use case).

We can fix it though

```bash
# Update the CHECK constraints to match the data type of the column
psql -h localhost --user pgslice_tester pgslice_test <<EOF
ALTER TABLE events_201701 DROP CONSTRAINT events_201701_occurred_at_check;
ALTER TABLE events_201701 ADD CHECK (occurred_at >= '2017-01-01'::timestamptz AND occurred_at < '2017-02-01'::timestamptz);

ALTER TABLE events_201612 DROP CONSTRAINT events_201612_occurred_at_check;
ALTER TABLE events_201612 ADD CHECK (occurred_at >= '2016-12-01'::timestamptz AND occurred_at < '2017-01-01'::timestamptz);

ALTER TABLE events_201611 DROP CONSTRAINT events_201611_occurred_at_check;
ALTER TABLE events_201611 ADD CHECK (occurred_at >= '2016-11-01'::timestamptz AND occurred_at < '2016-12-01'::timestamptz);

ALTER TABLE events_201610 DROP CONSTRAINT events_201610_occurred_at_check;
ALTER TABLE events_201610 ADD CHECK (occurred_at >= '2016-10-01'::timestamptz AND occurred_at < '2016-11-01'::timestamptz);
EOF
```

Now lets check those queries again
```bash
psql -h localhost --user pgslice_tester pgslice_test -c "EXPLAIN SELECT * FROM events WHERE occurred_at BETWEEN '2016-10-01 00:00:00-0' AND '2016-11-01 00:00:00-0';"
#                                                                          QUERY PLAN
#---------------------------------------------------------------------------------------------------------------------------------------------------------------
# Append  (cost=0.00..14.65 rows=3 width=230)
#   ->  Seq Scan on events  (cost=0.00..0.00 rows=1 width=230)
#         Filter: ((occurred_at >= '2016-09-30 20:00:00-04'::timestamp with time zone) AND (occurred_at <= '2016-10-31 20:00:00-04'::timestamp with time zone))
#   ->  Seq Scan on events_201610  (cost=0.00..14.65 rows=2 width=230)
#         Filter: ((occurred_at >= '2016-09-30 20:00:00-04'::timestamp with time zone) AND (occurred_at <= '2016-10-31 20:00:00-04'::timestamp with time zone))
#(5 rows)
```

Now the check constraints are used by the planner to avoid scanning unnecessary tables. **This is what I'm trying to accomplish.**

The second query `psql -h localhost --user pgslice_tester pgslice_test -c "EXPLAIN SELECT * FROM events WHERE occurred_at BETWEEN '2016-10-01'::date AND '2016-11-01'::date;"` is *not* optimized by the planner. I attribute this to comparing a `timestamptz` type to a `date` type

I also tried these variations of the query. In both cases they did a full scan of all child tables with pgslice's default CHECK constraints, but were optimized afterwards
```bash
psql -h localhost --user pgslice_tester pgslice_test -c "EXPLAIN SELECT * FROM events WHERE occurred_at BETWEEN '2016-10-01 00:00:00-0'::timestamptz AND '2016-11-01 00:00:00-0'::timestamptz;"
# This query still has to scan events_201611, but it's because I'm lazy and used BETWEEN
psql -h localhost --user pgslice_tester pgslice_test -c "EXPLAIN SELECT * FROM events WHERE occurred_at BETWEEN '2016-10-01' AND '2016-11-01';"
```

This was all done on a PostgreSQL 9.3

**Comment by ankane** [comment] 2016-10-20 03:36
Interesting, do you see the same behavior on 9.4?

**Comment by richardsmd** [comment] 2016-10-20 14:31
I see the same behavior on 9.5.

I don't have a 9.4 or a 9.6 instance of postgres to test on.

Based off my reading of the postgres documentation I believe the fundamental problem is the mismatch between non-date columns and the explicit `::date` cast pgslice provides.

**Comment by ankane** [comment] 2016-10-20 17:13
Hmm, we use a `timestamp` columns (instead of `timestamptz`) and the planner uses the constraints. If the issue is exclusive to `timestamptz`, we can pretty easily look up the column type and use different constraints for without any extra command line options. Happy to accept a PR for it.

**Comment by ankane** [comment] 2016-10-27 03:22
I just realized we need to understand how this impact backwards compatibility - essentially, what should happen if someone has already partitioned on a `timestamptz` column. Currently, they'll end up with some partitions with a `date` constraint and future ones with a `timestamptz`, which seems like it could be dangerous.

Until then, it'll default to the previous behavior 00920c5d88669e7383fefc18a3575becc111ce6b

**Comment by richardsmd** [comment] 2016-10-27 14:58
We already know what happens if the CHECK constraint is `::date` against a `timestamptz` column - no optimization. Queries still work, just slowly.

We also know that INSERT works correctly with the trigger with both `::date` and `::timestamptz`

Can you describe what you mean by _could be dangerous_? Some sort of boundary condition between a date and a timestamptz whereupon the CHECK constraints create a range of time where no inserts are allowable?

**Comment by ankane** [comment] 2016-10-27 15:32
Yeah, the boundary condition is what I'm thinking about.

**Comment by ankane** [comment] 2016-10-27 15:39
If it's not issue, great - we can release as is. If it is an issue, we'll need to continue to use the `date` type for those tables.

**Comment by richardsmd** [comment] 2016-10-27 16:26
How's this for quelling your concerns?

```bash
sudo -u postgres psql <<EOF
CREATE USER boundary_tester WITH PASSWORD 'boundary_tester';
DROP DATABASE IF EXISTS pgslice_boundary_test;
CREATE DATABASE pgslice_boundary_test;
GRANT ALL PRIVILEGES ON DATABASE pgslice_boundary_test to boundary_tester;
EOF

echo 'localhost:5432:pgslice_boundary_test:boundary_tester:boundary_tester' >> ~/.pgpass
chmod 600 ~/.pgpass

psql -h localhost --user boundary_tester pgslice_boundary_test <<EOF
CREATE TABLE events(
    id SERIAL,
    description VARCHAR(100),
    occurred_at timestamptz);
EOF

psql -h localhost --user boundary_tester pgslice_boundary_test -c "SELECT * FROM events"

export PGSLICE_URL='postgresql://boundary_tester:boundary_tester@localhost/pgslice_boundary_test'
pgslice prep events occurred_at month
pgslice add_partitions events --intermediate --future 3
pgslice swap events

# Simulate upgrade scenario
# All this is run with my local build that incorporates the PR I sent earlier.
# Since add_partitions updates the insert trigger all that needs to be done is to update an "old" table's CHECK condition
psql -h localhost --user boundary_tester pgslice_boundary_test << EOF
ALTER TABLE events_201612 DROP CONSTRAINT events_201612_occurred_at_check;
ALTER TABLE events_201612 ADD CHECK (occurred_at >= '2016-12-01'::date AND occurred_at < '2017-01-01'::date);
EOF



# PSQL timestamp resolution is 1 microsecond
#
generate_timestamps() {
    # Produces timestamps:
    # 2016-12-31 23:59:59.000000
    # 2016-12-31 23:59:59.000001
    # 2016-12-31 23:59:59.000002
    # 2016-12-31 23:59:59.000003
    # 2016-12-31 23:59:59.000004
    # 2016-12-31 23:59:59.000005
    # 2016-12-31 23:59:59.000006
    # 2016-12-31 23:59:59.000007
    # 2016-12-31 23:59:59.000008
    # 2016-12-31 23:59:59.000009
    # ...
    # 2017-01-01 00:00:00.999990
    # 2017-01-01 00:00:00.999991
    # 2017-01-01 00:00:00.999992
    # 2017-01-01 00:00:00.999993
    # 2017-01-01 00:00:00.999994
    # 2017-01-01 00:00:00.999995
    # 2017-01-01 00:00:00.999996
    # 2017-01-01 00:00:00.999997
    # 2017-01-01 00:00:00.999998
    # 2017-01-01 00:00:00.999999
    for DATE in '2016-12-31' '2017-01-01'; do
        for HOUR_MINUTE_SECOND in "23:59:59" "00:00:00"; do
            for MICRO in $(seq -f "%06g" 0 999999); do
                echo "$DATE $HOUR_MINUTE_SECOND.$MICRO"
            done
        done
    done
}

generate_timestamps | awk 'BEGIN {print "INSERT INTO events (description, occurred_at) VALUES"} {print "(\47foo\47, \47" $0 "\47::timestamptz),"} END {print "(\47baz\47, \47" "2017-01-23 04:56:07\47::timestamptz);"}' | psql -h localhost --user boundary_tester pgslice_boundary_test
```

If you're not familiar with awk, here's the output of `generate_timestamps | head | awk 'BEGIN {print "INSERT INTO events (description, occurred_at) VALUES"} {print "(\47foo\47, \47" $0 "\47::timestamptz),"} END {print "(\47baz\47, \47" "2017-01-23 04:56:07\47::timestamptz);"}'`

```
INSERT INTO events (description, occurred_at) VALUES
('foo', '2016-12-31 23:59:59.000000'::timestamptz),
('foo', '2016-12-31 23:59:59.000001'::timestamptz),
('foo', '2016-12-31 23:59:59.000002'::timestamptz),
('foo', '2016-12-31 23:59:59.000003'::timestamptz),
('foo', '2016-12-31 23:59:59.000004'::timestamptz),
('foo', '2016-12-31 23:59:59.000005'::timestamptz),
('foo', '2016-12-31 23:59:59.000006'::timestamptz),
('foo', '2016-12-31 23:59:59.000007'::timestamptz),
('foo', '2016-12-31 23:59:59.000008'::timestamptz),
('foo', '2016-12-31 23:59:59.000009'::timestamptz),
('baz', '2017-01-23 04:56:07'::timestamptz);
```

Now, if this all worked we should have 4000001 records

- 1 record per inner loop (1M per second) * 2 middle loops * 2 outer loops
- 1 record from the AWK script (from `END`)

```
 psql -h localhost --user boundary_tester pgslice_boundary_test -c 'SELECT COUNT(1) FROM events;'
  count
---------
 4000001
(1 row)
```

Per the [postgres docs](https://www.postgresql.org/docs/9.4/static/functions-datetime.html) leap seconds are not handled, so there's no trickery there.

In case you're concerned about specifics of where the data went

```
 psql -h localhost --user boundary_tester pgslice_boundary_test -c 'SELECT COUNT(1) FROM ONLY events_201612;'
#   count
# ---------
#  2000000
# (1 row)

psql -h localhost --user boundary_tester pgslice_boundary_test -c 'SELECT COUNT(1) FROM ONLY events_201701;'
#   count
# ---------
#  2000001
# (1 row)
```

**Comment by ankane** [comment] 2016-10-28 04:34
Thanks for putting this together. I ended up running tests for each minute of the day between 12/31 and 1/2 with different server time zone values and `timestamptz` time zone values to confirm. Also, this is comforting, fwiw.

```sql
select '2016-01-01'::date = '2016-01-01'::timestamptz AS okay;
 okay 
------
 t
```

I'll update and push a new release. Thanks for all the work on this! 💯

**Comment by ankane** [comment] 2016-10-28 04:57
My bad, messed something up. I was actually able to get this to fail by setting the server time zone to `Europe/Oslo`, the client time zone to `Australia/Brisbane`, and running [this Ruby code](https://gist.github.com/ankane/88d97a24beb1542f33419dab603da039).

Having mismatched constraints just feels like a bad idea. I think a safer approach is when a `timestamptz` column is encountered, check the existing trigger uses `date`. If so, it should use `date` as well.

**Comment by richardsmd** [comment] 2016-11-04 14:50
Changing the timezone of the server **after** creating the insert trigger causes the timezone of the trigger to change because the timezone was not explicitly set in the trigger code. Instead, server time is used at execution. 

Meanwhile, the check constraints **do not** change. The timezone also defaults to server time when the check is created, but is persisted and does not change as the server timezone changes. This creates the boundary error condition your test uncovered.

The patch fixes this by:
1. adding cast information to the trigger comment in a backwards-compatible way (defaulting to `date` for existing installations)
1. Explicitly setting a timezone on the trigger and check, so that altering server time doesn't de-sync the trigger and the check constraints

The patch explicitly sets both the trigger and the check constraint time zones to UTC. I'd have rather set it to the server time *but* I ran into the common case of Postgres using `localtime` (the host OS time zone) which is difficult to determine in a platform-independent way. This would also require adding the timezone to the trigger comment to prevent the same boundary condition from potentially occurring

**Comment by ankane** [comment] 2016-12-13 06:53
Finally merged! 🎉

**Closed by ankane** 2016-12-13 06:53 UTC
